class Util:
    self.syracuse_max_date = 191
    self.syracuse_max_state = 53
    self.syracuse_mappings = {[
        {'state' :'Texas',
        'code' : 2,
        'cities' : [
            {'city' : 'Laredo',
            'code' : 10},
            {'city' : 'El Paso',
            'code' : 2},
            {'city' : 'Harlingen',
            'code' : 36},
            {'city' : 'Del Rio',
            'code' : 27},
            {'city' : 'Brownsville',
            'code' : 15},
            {'city' : 'Huston',
            'code' : 9},
            {'city' : 'San Antonio',
            'code' : 104},
            {'city' : 'Hidalgo',
            'code' : 19},
            {'city' : 'Valley International Airport',
            'code' : 302},
            {'city' : 'Paso del Norte',
            'code' : 11},
            {'city' : 'Brownsville-Matamor',
            'code' : 124},
            {'city' : 'Dallas',
            'code' : 14},
            {'city' : 'Eagle Pass',
            'code' : 113},
            {'city' : 'Laredo Columbia Bridge',
            'code' : 123},
            {'city' : 'Dallas',
            'code' : 14},
            {'city' : 'Eagle Pass, International Bridge #2',
            'code' : 132},
            {'city' : 'Presidio',
            'code' : 60},
            {'city' : 'Progreso',
            'code' : 77},
            {'city' : 'Bridge of Americas',
            'code' : 71},
            {'city' : 'Austin',
            'code' : 165},
            {'city' : 'Ysleta',
            'code' : 38},
            {'city' : 'Corpus Christi',
            'code' : 173},
            {'city' : 'Rio Grande City',
            'code' : 15},
            {'city' : 'Los Indios (Free Trade Brigade)',
            'code' : 62},
            {'city' : 'Veterans International Bridge',
            'code' : 217},
            {'city' : 'Stanton ST Bridge',
            'code' : 221},
            {'city' : 'Port Isabel',
            'code' : 349},
            {'city' : 'Pharr',
            'code' : 83},
            {'city' : 'Port of El Paso',
            'code' : 114},
            {'city' : 'Galveston',
            'code' : 234},
            {'city' : 'Donna',
            'code' : 331},
            {'city' : 'Hobby Airport',
            'code' : 237},
            {'city' : 'Fort Hancock',
            'code' : 160},
            {'city' : 'Anzaludas Crossing Port of Entry',
            'code' : 223},
            {'city' : 'Los Ebanos',
            'code' : 180},
            {'city' : 'Amistad Dam',
            'code' : 251},
            {'city' : 'Falcon Heights',
            'code' : 72},
            {'city' : 'Port Arthur',
            'code' : 224},
            {'city' : 'Laredo, World Trade Bridge',
            'code' : 317},
            {'city' : 'Freeport',
            'code' : 194}
        ]},
        {'state' :'California',
        'code' : 7,
        'cities' : [
            {'city' : 'San Ysidro',
            'code' : 21},
            {'city' : 'Calexico',
            'code' : 21},
            {'city' : 'Los Angeles',
            'code' : 7},
            {'city' : 'Otay Mesa',
            'code' : 12},
            {'city' : 'San Francisco',
            'code' : 13},
            {'city' : 'Los Angeles, Airport',
            'code' : 348},
            {'city' : 'San Diego, Airport',
            'code' : 26},
            {'city' : 'San Jose',
            'code' : 96},
            {'city' : 'Tecate',
            'code' : 88},
            {'city' : 'Sacramento',
            'code' : 154},
            {'city' : 'San Diego',
            'code' : 193},
            {'city' : 'Andrade',
            'code' : 119},
            {'city' : 'Calexico-East',
            'code' : 169},
            {'city' : 'Oakland',
            'code' : 212},
            {'city' : 'San Pedro',
            'code' : 80},
            {'city' : 'Ontario International Aiproirt',
            'code' : 179},
            {'city' : 'Fresno',
            'code' : 243},
            {'city' : 'Long Beach(Seaport/Poe)',
            'code' : 266},
            {'city' : 'Otay Cross Border Express',
            'code' : 373},
            {'city' : 'Ventura',
            'code' : 326},
            {'city' : 'John Wayne Airport',
            'code' : 372},
            {'city' : 'Campo',
            'code' : 375}
        ]},
        {'state' :'Arizona',
        'code' : 4,
        'cities' : [
            {'city' : 'Nogales',
            'code' : 4},
            {'city' : 'Phoenix',
            'code' : 8},
            {'city' : 'Tucson',
            'code' : 79},
            {'city' : 'San Luis',
            'code' : 32},
            {'city' : 'Douglas',
            'code' : 68},
            {'city' : 'Naco',
            'code' : 65},
            {'city' : 'Sasabe',
            'code' : 111},
            {'city' : 'Lukeville',
            'code' : 78},
            {'city' : 'Mariposa',
            'code' : 220},
            {'city' : 'Yuma',
            'code' : 202},
            {'city' : 'Morley Gate',
            'code' : 254}
        ]},
        {'state' :'Louisiana',
        'code' : 1,
        'cities' : [
            {'city' : 'New Orleans International Airport',
            'code' : 1},
            {'city' : 'Alexandria International Airport',
            'code' : 361},
            {'city' : 'Lake Charles',
            'code' : 126},
            {'city' : 'Baton Rouge',
            'code' : 108},
            {'city' : 'New Orleans Airport',
            'code' : 190}
        ]},
        {'state' :'Florida',
        'code' : 5,
        'cities' : [
            {'city' : 'Maiami International Airport, Miami',
            'code' : 5},
            {'city' : 'Fort Lauderdale',
            'code' : 69},
            {'city' : 'Orlando',
            'code' : 42},
            {'city' : 'Tampa',
            'code' : 17},
            {'city' : 'Miami Seaport',
            'code' : 350},
            {'city' : 'Jacksonville',
            'code' : 155},
            {'city' : 'Sanford',
            'code' : 196},
            {'city' : 'Port Everglades',
            'code' : 133},
            {'city' : 'Cape Canaveral',
            'code' : 141},
            {'city' : 'West Palm Beach',
            'code' : 157},
            {'city' : 'Panama City',
            'code' : 214},
            {'city' : 'Fort Myers',
            'code' : 182},
            {'city' : 'Pensacola',
            'code' : 218},
            {'city' : 'Key West',
            'code' : 187},
            {'city' : 'Fort Pierce',
            'code' : 136},
            {'city' : 'Naples, FL Port of Entry',
            'code' : 370}
        ]},
        {'state' :'New York',
        'code' : 5,
        'cities' : [
            {'city' : 'New York',
            'code' : 20},
            {'city' : 'New York (Kennedy)',
            'code' : 344},
            {'city' : 'Buffalo',
            'code' : 34},
            {'city' : 'Peace Bridge',
            'code' : 55},
            {'city' : 'Alexandria Bay',
            'code' : 103},
            {'city' : 'Rainbow Bridge',
            'code' : 57},
            {'city' : 'Champlain',
            'code' : 59},
            {'city' : 'Niagra Falls',
            'code' : 40},
            {'city' : 'Lewiston (Queenstone Bridge)',
            'code' : 131},
            {'city' : 'Albany',
            'code' : 105},
            {'city' : 'Ogdensburg',
            'code' : 175},
            {'city' : 'Thousand Island Bridge',
            'code' : 184},
            {'city' : 'Massena',
            'code' : 91},
            {'city' : 'Trout River',
            'code' : 242},
            {'city' : 'Syracuse',
            'code' : 296},
            {'city' : 'Rouses Point',
            'code' : 167},
            {'city' : 'Chateugay',
            'code' : 279},
            {'city' : 'Fort Covington',
            'code' : 272},
            {'city' : 'Cannon Corners',
            'code' : 310},
            {'city' : 'Churubusco',
            'code' : 334},
            {'city' : 'Wellesley Island',
            'code' : 335},
            {'city' : 'Overton Corners',
            'code' : 107},
            {'city' : 'Jamiston Lane',
            'code' : 230},
            {'city' : 'New York, LaGuardia',
            'code' : 257},
            {'city' : 'Clayton',
            'code' : 178},
            {'city' : 'Whirlpool Bridge',
            'code' : 316},
            {'city' : 'Cape Vincent',
            'code' : 341},
            {'city' : 'Rochester',
            'code' : 358},
        ]},
        {'state' :'Georgia',
        'code' : 8,
        'cities' : [
            {'city' : 'Hartsfield International Airport',
            'code' : 18},
            {'city' : 'Atlanta, Airport',
            'code' : 346},
            {'city' : 'Brunswick',
            'code' : 162},
            {'city' : 'Savannah',
            'code' : 236}
        ]},
        {'state' :'New Jersey',
        'code' : 13,
        'cities' : [
            {'city' : 'Newark International Airport',
            'code' : 28},
            {'city' : 'Cherry Hill',
            'code' : 275},
            {'city' : 'Atlantic City International Airport',
            'code' : 357}
        ]},
        {'state' :'Illinois',
        'code' : 6,
        'cities' : [
            {'city' : "Chicago-O'Hare International Airport",
            'code' : 6},
            {'city' : 'Midway (Chicago)',
            'code' : 288}
        ]},
        {'state' :'District of Columbia',
        'code' : 11,
        'cities' : [
            {'city' : 'Dulles International Airport',
            'code' : 24}
        ]},
        {'state' :'Unknown',
        'code' : 22,
        'cities' : [
            {'city' : 'Unknown',
            'code' : 46}
        ]},
        {'state' :'Michigan',
        'code' : 10,
        'cities' : [
            {'city' : 'Detroit',
            'code' : 23},
            {'city' : 'Detroit (Airport)',
            'code' : 101},
            {'city' : 'Oakland COunty International Airport',
            'code' : 177},
            {'city' : 'Detroit (Tunnel)',
            'code' : 142},
            {'city' : 'Detroit (Bridge)',
            'code' : 41},
            {'city' : 'Port Huron',
            'code' : 97},
            {'city' : 'Saul St. Marie',
            'code' : 158},
            {'city' : 'Algonac',
            'code' : 323},
            {'city' : 'Marine City',
            'code' : 267},
            {'city' : 'Grand Rapids Port of Entry',
            'code' : 359},
            {'city' : 'Alpena',
            'code' : 171},
            {'city' : 'St. Clair',
            'code' : 303},
            {'city' : 'Fort Street Cargo Facility',
            'code' : 362},
            {'city' : 'Port of Battle Creek',
            'code' : 380}
        ]},
        {'state' :'Puerto Rico',
        'code' : 15,
        'cities' : [
            {'city' : 'Saj/A Antonio Rivera-Rodrigues Airport',
            'code' : 30},
            {'city' : 'Luis Munoz Marin International Airport',
            'code' : 345},
            {'city' : 'San Juan',
            'code' : 347},
            {'city' : 'Aguadilla',
            'code' : 53},
            {'city' : 'Mayagues',
            'code' : 87},
            {'city' : 'Ponce',
            'code' : 204},
            {'city' : 'Benjamin Rivera Noriega Airport - Culebra',
            'code' : 337}
        ]},
        {'state' :'New Mexico',
        'code' : 19,
        'cities' : [
            {'city' : 'Albuquerque',
            'code' : 151},
            {'city' : 'Columbus',
            'code' : 37},
            {'city' : 'Santa Teresa',
            'code' : 127},
            {'city' : 'Antelope Wells',
            'code' : 262}
        ]},
        {'state' :'Massachusetts',
        'code' : 12,
        'cities' : [
            {'city' : 'Logan International Airport, Boston',
            'code' : 25},
            {'city' : 'Boston (Logan)',
            'code' : 352}
        ]},
        {'state' :'Washington',
        'code' : 23,
        'cities' : [
            {'city' : 'Seattle',
            'code' : 47},
            {'city' : 'Blaine',
            'code' : 64},
            {'city' : 'Seattle (Seaport)',
            'code' : 112},
            {'city' : 'Pacific Highway',
            'code' : 128},
            {'city' : 'Tacoma',
            'code' : 48},
            {'city' : 'Nighthawk',
            'code' : 140},
            {'city' : 'Oroville',
            'code' : 56},
            {'city' : 'Sumas',
            'code' : 89},
            {'city' : 'Melaine Falls',
            'code' : 231},
            {'city' : 'Port Angeles',
            'code' : 256},
            {'city' : 'Lynden',
            'code' : 153},
            {'city' : 'Bellingham',
            'code' : 161},
            {'city' : 'Laurier',
            'code' : 210},
            {'city' : 'Longview',
            'code' : 152},
            {'city' : 'Boundary',
            'code' : 229},
            {'city' : 'Point Roberts',
            'code' : 258},
            {'city' : 'Frontier',
            'code' : 125},
            {'city' : 'Aberdeen',
            'code' : 246},
            {'city' : 'Anacortes',
            'code' : 227},
            {'city' : 'Danville',
            'code' : 232},
            {'city' : 'Vancouver',
            'code' : 75},
            {'city' : 'Spokane',
            'code' : 325},
            {'city' : 'Kalama',
            'code' : 226},
            {'city' : 'Neah Bay',
            'code' : 213},
            {'city' : 'Ferry',
            'code' : 164},
            {'city' : 'Everett',
            'code' : 378},
        ]},
        {'state' :'Virgin Islands',
        'code' : 16,
        'cities' : [
            {'city' : 'Charlotte Amalie, St. Thomas, VI',
            'code' : 31},
            {'city' : 'Christiansted, St. Croix',
            'code' : 74},
            {'city' : 'Crus Bay, Jt. John VI',
            'code' : 314}
        ]},
        {'state' :'Pennsylvania',
        'code' : 14,
        'cities' : [
            {'city' : 'Philadelphia International Airport, Philadelphia',
            'code' : 29},
            {'city' : 'Pittsburg International Airport, Philadelphia',
            'code' : 115},
            {'city' : 'Harrisburg',
            'code' : 354},
            {'city' : 'Erie',
            'code' : 174}
        ]},
        {'state' :'Minnesota',
        'code' : 17,
        'cities' : [
            {'city' : 'St. Paul',
            'code' : 45},
            {'city' : 'Duluth',
            'code' : 44},
            {'city' : 'Minneapolis/St. Paul',
            'code' : 33},
            {'city' : 'Noyes',
            'code' : 260},
            {'city' : 'Ely',
            'code' : 176},
            {'city' : 'Lancaster',
            'code' : 205},
            {'city' : 'International Falls',
            'code' : 166},
            {'city' : 'Grand Portage',
            'code' : 238},
            {'city' : 'Pine Creek',
            'code' : 159},
            {'city' : 'Baudette',
            'code' : 120},
            {'city' : 'Warroad',
            'code' : 245},
            {'city' : 'Crane Lake',
            'code' : 295},
            {'city' : 'Roseau',
            'code' : 286},
            {'city' : 'Pinecreek Port of Entry',
            'code' : 360}
        ]},
        {'state' :'North Carolina',
        'code' : 34,
        'cities' : [
            {'city' : 'Charlotte',
            'code' : 100},
            {'city' : 'Wilmington',
            'code' : 81},
            {'city' : 'Raleigh/Durham',
            'code' : 110},
            {'city' : 'Morehead City',
            'code' : 320}
        ]},
        {'state' :'Hawaii',
        'code' : 30,
        'cities' : [
            {'city' : 'Honolulu',
            'code' : 67},
            {'city' : 'Keahole-Kona',
            'code' : 311},
            {'city' : 'Lihue',
            'code' : 367}
        ]},
        {'state' :'Colorado',
        'code' : 27,
        'cities' : [
            {'city' : 'Denver',
            'code' : 52}
        ]},
        {'state' :'Guam',
        'code' : 20,
        'cities' : [
            {'city' : 'Agana',
            'code' : 39}
        ]},
        {'state' :'Connecticut',
        'code' : 24,
        'cities' : [
            {'city' : 'Hartford',
            'code' : 49},
            {'city' : 'New Haven',
            'code' : 351},
            {'city' : 'New London',
            'code' : 353},
            {'city' : 'Bridgeport',
            'code' : 369},
            {'city' : 'Groton',
            'code' : 252}
        ]},
        {'state' :'Maryland',
        'code' : 21,
        'cities' : [
            {'city' : 'Baltimore, South Locust Point Marine Terminal',
            'code' : 43},
            {'city' : 'Baltimore Airport',
            'code' : 363},
            {'city' : 'Andrews AFB',
            'code' : 294},
            {'city' : 'Patuxent River',
            'code' : 308}
        ]},
        {'state' :'Nevada',
        'code' : 26,
        'cities' : [
            {'city' : 'Las Vegas',
            'code' : 51},
            {'city' : 'Reno',
            'code' : 54}
        ]},
        {'state' :'Ohio',
        'code' : 18,
        'cities' : [
            {'city' : 'Griffing Airport, Sandusky',
            'code' : 253},
            {'city' : 'Toledo',
            'code' : 85},
            {'city' : 'Cleveland',
            'code' : 66},
            {'city' : 'Cincinnati',
            'code' : 35},
            {'city' : 'Columbus',
            'code' : 150},
            {'city' : 'Loraine',
            'code' : 147},
            {'city' : 'Arkon',
            'code' : 366},
            {'city' : 'Ashtabula',
            'code' : 368}
        ]},
        {'state' :'Oregon',
        'code' : 3,
        'cities' : [
            {'city' : 'Las Vegas',
            'code' : 51},
            {'city' : 'Reno',
            'code' : 54}
        ]},











    ]}
