import React from "react";
import logo from "../logo.svg";
import Container from 'react-bootstrap/Container';
import Row from 'react-bootstrap/Row';
import Col from 'react-bootstrap/Col';

export default function About() {
  return (
    <div className="about">
      <header className="about-header my-3">
        <img src={logo} className="about-logo" alt="logo" />
        <p>
          <a href="/">ai.melts.ice</a>
        </p>

        <p className="about-main">El pueblo unido jamás será vencido.</p>
      </header>

      <main className="about-main">
        <Container>
          <Row>
            <Col sm={{ order: 1 }}>
              <p><a href="/">ai.melts.ice</a> is a web app designed to source and
              visualize predictions of ICE arrests in the US by county. These predictions
              are generated by an LSTM neural network trained on data
              (2014 - 2018) from Syracuse's TRAC web API. Please keep in mind that
              any data shown past 2018 are predictions and may not be exact.</p>
            </Col>
            <Col sm={{ order: 3 }}>
              <p><a href="/">ai.melts.ice</a> es una aplicación web designada para
              para producir y visualizar predicciones de arrestos de inmigrantes en los
              Estados Unidos por condado. Estas predicciones son generadas
              por una red neural LSTM entrenada con datos (2014 - 2018) del
              web API TRAC de Syracuse. Por favor tengan en cuenta que los datos
              después de 2018 son predicciones y pueden ser inexactos.</p>
            </Col>
          </Row>
        </Container>
      </main>
    </div>
  );
}
